name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./.github/workflows/terraform_install.sh
      - run: cd ~/ && terraform init && terraform apply -auto-approve
     
